/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AutomotiveDataSolutionsAdminRouteImport } from './routes/automotive-data-solutions-admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppManageRouteImport } from './routes/_app.manage'
import { Route as AppHitlRouteImport } from './routes/_app.hitl'
import { Route as AppCapabilitiesRouteImport } from './routes/_app.capabilities'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSolutionsIndexRouteImport } from './routes/_app.solutions.index'
import { Route as AppCapabilitiesIndexRouteImport } from './routes/_app.capabilities.index'
import { Route as AppSolutionsIdRouteImport } from './routes/_app.solutions.$id'
import { Route as AppCapabilitiesIdRouteImport } from './routes/_app.capabilities.$id'

const AutomotiveDataSolutionsAdminRoute =
  AutomotiveDataSolutionsAdminRouteImport.update({
    id: '/automotive-data-solutions-admin',
    path: '/automotive-data-solutions-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppHitlRoute = AppHitlRouteImport.update({
  id: '/hitl',
  path: '/hitl',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesRoute = AppCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSolutionsIndexRoute = AppSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesIndexRoute = AppCapabilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCapabilitiesRoute,
} as any)
const AppSolutionsIdRoute = AppSolutionsIdRouteImport.update({
  id: '/solutions/$id',
  path: '/solutions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesIdRoute = AppCapabilitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCapabilitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/automotive-data-solutions-admin': typeof AutomotiveDataSolutionsAdminRoute
  '/admin': typeof AppAdminRoute
  '/capabilities': typeof AppCapabilitiesRouteWithChildren
  '/hitl': typeof AppHitlRoute
  '/manage': typeof AppManageRoute
  '/capabilities/$id': typeof AppCapabilitiesIdRoute
  '/solutions/$id': typeof AppSolutionsIdRoute
  '/capabilities/': typeof AppCapabilitiesIndexRoute
  '/solutions/': typeof AppSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/automotive-data-solutions-admin': typeof AutomotiveDataSolutionsAdminRoute
  '/admin': typeof AppAdminRoute
  '/hitl': typeof AppHitlRoute
  '/manage': typeof AppManageRoute
  '/': typeof AppIndexRoute
  '/capabilities/$id': typeof AppCapabilitiesIdRoute
  '/solutions/$id': typeof AppSolutionsIdRoute
  '/capabilities': typeof AppCapabilitiesIndexRoute
  '/solutions': typeof AppSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/automotive-data-solutions-admin': typeof AutomotiveDataSolutionsAdminRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/capabilities': typeof AppCapabilitiesRouteWithChildren
  '/_app/hitl': typeof AppHitlRoute
  '/_app/manage': typeof AppManageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/capabilities/$id': typeof AppCapabilitiesIdRoute
  '/_app/solutions/$id': typeof AppSolutionsIdRoute
  '/_app/capabilities/': typeof AppCapabilitiesIndexRoute
  '/_app/solutions/': typeof AppSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automotive-data-solutions-admin'
    | '/admin'
    | '/capabilities'
    | '/hitl'
    | '/manage'
    | '/capabilities/$id'
    | '/solutions/$id'
    | '/capabilities/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/automotive-data-solutions-admin'
    | '/admin'
    | '/hitl'
    | '/manage'
    | '/'
    | '/capabilities/$id'
    | '/solutions/$id'
    | '/capabilities'
    | '/solutions'
  id:
    | '__root__'
    | '/_app'
    | '/automotive-data-solutions-admin'
    | '/_app/admin'
    | '/_app/capabilities'
    | '/_app/hitl'
    | '/_app/manage'
    | '/_app/'
    | '/_app/capabilities/$id'
    | '/_app/solutions/$id'
    | '/_app/capabilities/'
    | '/_app/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AutomotiveDataSolutionsAdminRoute: typeof AutomotiveDataSolutionsAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/automotive-data-solutions-admin': {
      id: '/automotive-data-solutions-admin'
      path: '/automotive-data-solutions-admin'
      fullPath: '/automotive-data-solutions-admin'
      preLoaderRoute: typeof AutomotiveDataSolutionsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hitl': {
      id: '/_app/hitl'
      path: '/hitl'
      fullPath: '/hitl'
      preLoaderRoute: typeof AppHitlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities': {
      id: '/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AppCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solutions/': {
      id: '/_app/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof AppSolutionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities/': {
      id: '/_app/capabilities/'
      path: '/'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof AppCapabilitiesIndexRouteImport
      parentRoute: typeof AppCapabilitiesRoute
    }
    '/_app/solutions/$id': {
      id: '/_app/solutions/$id'
      path: '/solutions/$id'
      fullPath: '/solutions/$id'
      preLoaderRoute: typeof AppSolutionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities/$id': {
      id: '/_app/capabilities/$id'
      path: '/$id'
      fullPath: '/capabilities/$id'
      preLoaderRoute: typeof AppCapabilitiesIdRouteImport
      parentRoute: typeof AppCapabilitiesRoute
    }
  }
}

interface AppCapabilitiesRouteChildren {
  AppCapabilitiesIdRoute: typeof AppCapabilitiesIdRoute
  AppCapabilitiesIndexRoute: typeof AppCapabilitiesIndexRoute
}

const AppCapabilitiesRouteChildren: AppCapabilitiesRouteChildren = {
  AppCapabilitiesIdRoute: AppCapabilitiesIdRoute,
  AppCapabilitiesIndexRoute: AppCapabilitiesIndexRoute,
}

const AppCapabilitiesRouteWithChildren = AppCapabilitiesRoute._addFileChildren(
  AppCapabilitiesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCapabilitiesRoute: typeof AppCapabilitiesRouteWithChildren
  AppHitlRoute: typeof AppHitlRoute
  AppManageRoute: typeof AppManageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSolutionsIdRoute: typeof AppSolutionsIdRoute
  AppSolutionsIndexRoute: typeof AppSolutionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCapabilitiesRoute: AppCapabilitiesRouteWithChildren,
  AppHitlRoute: AppHitlRoute,
  AppManageRoute: AppManageRoute,
  AppIndexRoute: AppIndexRoute,
  AppSolutionsIdRoute: AppSolutionsIdRoute,
  AppSolutionsIndexRoute: AppSolutionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AutomotiveDataSolutionsAdminRoute: AutomotiveDataSolutionsAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
